### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by marcolinux46** [Tib612/pluxee-api#1]
Hi,

I used the library with an italian account but i received a SSL error.
Can you help you to resolve this issue?
I'm interested to work with this library
![1718006480206144451513174845342](https://github.com/Tib612/pluxee-api/assets/65719155/6096dfaf-1fc4-4d01-aa2f-24ed2f886a22)

**Comment by marcolinux46** [comment]
If you want i can help you to improve the library for italian users

**Comment by Tib612** [comment]
Hi Marcolinux46,

Thanks for your message. I could reproduce the error.
I will try to solve it this evening.

**Comment by Tib612** [comment]
> If you want i can help you to improve the library for italian users

Thank you, if you help me, I can make it work with Italian users. It seems the login method is different from Belgium though.
On which website (URL) do you check your balance ?

Also, if the HTML is different, I will probably need the HTML of the page so I can extract the data and maybe some screenshot. (Don't forget to hide and remove sensible info like name, balance). I'll add a wiki with the info I need to make it work on other countries.

**Comment by marcolinux46** [comment]
I @Tib612 ,

Thank you for your answer.
I will provide you all the informations

**Comment by marcolinux46** [comment]
Do you need the URL from website not from the android app right?

**Comment by marcolinux46** [comment]
So,

from website you have to go on:

https://buoni.clienti.pluxee.it/

and click on login

![image](https://github.com/Tib612/pluxee-api/assets/65719155/81dbac6a-789d-4a62-ad20-cf9ef933d967)

[login.txt](https://github.com/user-attachments/files/15817870/login.txt)

**Comment by marcolinux46** [comment]
Clicked Login button you will find the authentication phase with email

![image](https://github.com/Tib612/pluxee-api/assets/65719155/8253d105-11e5-424e-bf5d-8faac2ec6a89)

**Comment by marcolinux46** [comment]
And after the password

![image](https://github.com/Tib612/pluxee-api/assets/65719155/6234abc5-9ce2-4872-a952-d171257dceaa)

**Comment by marcolinux46** [comment]
and this is the finale page

![image](https://github.com/Tib612/pluxee-api/assets/65719155/06e3ae3c-60e0-4233-89ea-ebd5e6bdfbd1)

**Comment by marcolinux46** [comment]
I will send you the html for:

**balance**:
[balance-movements.txt](https://github.com/user-attachments/files/15817747/balance-movements.txt)

![image](https://github.com/Tib612/pluxee-api/assets/65719155/a767335e-0231-4c8b-ba81-7d81078ff62f)

**Comment by marcolinux46** [comment]
**Movements**

[movements-searchmovements.txt](https://github.com/user-attachments/files/15817822/movements-searchmovements.txt)

![image](https://github.com/Tib612/pluxee-api/assets/65719155/afbe9a74-d3e6-4109-afe5-93db808542ae)

**Comment by marcolinux46** [comment]
I think this is a good starting point...

Let me know if you need something else.

**Comment by Tib612** [comment]
Thanks for the infos. I started working on a fix for the SSL and to add data retrieval for Italy.

What is the URL (path) for the transactions ("movimenti") ?

I will need the GET/POST request made to retrieve the balance and transactions. The payload should be enough I think. It can be found in the network tab of your chrome dev tool.

I will make a PR when the parsing of the HTML and the login are ready.

**Comment by marcolinux46** [comment]
Hi @Tib612 ,

this is the url for the Transactions("movimenti")

https://buoni.clienti.pluxee.it/BPE/Movimenti.aspx

For balance and transactions in the network tab i have more than one payload in GET request.

Balance:

RequestUrl:
https://buoni.clienti.pluxee.it/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZD3YJONjE4lo8ThtpREC3HB4pnteSA8d4ONQjSOhqw1LPb6rvzXosMX4MfRabbMVGg2&t=638259476865233147

Payload:
pynGkmcFUV13He1Qd6_TZD3YJONjE4lo8ThtpREC3HB4pnteSA8d4ONQjSOhqw1LPb6rvzXosMX4MfRabbMVGg2

RequestUrl:
https://buoni.clienti.pluxee.it/ScriptResource.axd?d=uHIkleVeDJf4xS50Krz-yGxjMpHXjadahB0rKxMU_4Fu96evfGUXXRtGIM4fY3KTLh9vtqikxuuY7wgdbtxvH7N57Qiu_NH38s0hptlNmbB5f3mY-EgSiShzMUMMcU-BrFUy2ASJWmNVcGqTT5M1ukXd7YGAoMMShpn-i9rFtxw1&t=ffffffffb1d0f179

Payload:
uHIkleVeDJf4xS50Krz-yGxjMpHXjadahB0rKxMU_4Fu96evfGUXXRtGIM4fY3KTLh9vtqikxuuY7wgdbtxvH7N57Qiu_NH38s0hptlNmbB5f3mY-EgSiShzMUMMcU-BrFUy2ASJWmNVcGqTT5M1ukXd7YGAoMMShpn-i9rFtxw1

RequestUrl:
https://buoni.clienti.pluxee.it/ScriptResource.axd?d=Jw6tUGWnA15YEa3ai3FadGNXHx_DYc5p546xV4lr7BBOr0hJBeoR4VyPxP2lYb82jFgF-SGHgVDsqfQJNr54W8-PvQSburFzEXgaAe3Mrt6G4tMKZ4YLU9MnsTLZCV_SUQcf-asqgvppo4VJoDVLdj4beuHunu0djNlO_vzYb5c1&t=ffffffffb1d0f179

Payload:
Jw6tUGWnA15YEa3ai3FadGNXHx_DYc5p546xV4lr7BBOr0hJBeoR4VyPxP2lYb82jFgF-SGHgVDsqfQJNr54W8-PvQSburFzEXgaAe3Mrt6G4tMKZ4YLU9MnsTLZCV_SUQcf-asqgvppo4VJoDVLdj4beuHunu0djNlO_vzYb5c1

Transaction

RequestUrl:
https://buoni.clienti.pluxee.it/WebResource.axd?d=pynGkmcFUV13He1Qd6_TZD3YJONjE4lo8ThtpREC3HB4pnteSA8d4ONQjSOhqw1LPb6rvzXosMX4MfRabbMVGg2&t=638259476865233147

Payload:
pynGkmcFUV13He1Qd6_TZD3YJONjE4lo8ThtpREC3HB4pnteSA8d4ONQjSOhqw1LPb6rvzXosMX4MfRabbMVGg2

RequestUrl:
https://buoni.clienti.pluxee.it/ScriptResource.axd?d=uHIkleVeDJf4xS50Krz-yGxjMpHXjadahB0rKxMU_4Fu96evfGUXXRtGIM4fY3KTLh9vtqikxuuY7wgdbtxvH7N57Qiu_NH38s0hptlNmbB5f3mY-EgSiShzMUMMcU-BrFUy2ASJWmNVcGqTT5M1ukXd7YGAoMMShpn-i9rFtxw1&t=ffffffffb1d0f179

Payload:
uHIkleVeDJf4xS50Krz-yGxjMpHXjadahB0rKxMU_4Fu96evfGUXXRtGIM4fY3KTLh9vtqikxuuY7wgdbtxvH7N57Qiu_NH38s0hptlNmbB5f3mY-EgSiShzMUMMcU-BrFUy2ASJWmNVcGqTT5M1ukXd7YGAoMMShpn-i9rFtxw1

RequestUrl:
https://buoni.clienti.pluxee.it/ScriptResource.axd?d=Jw6tUGWnA15YEa3ai3FadGNXHx_DYc5p546xV4lr7BBOr0hJBeoR4VyPxP2lYb82jFgF-SGHgVDsqfQJNr54W8-PvQSburFzEXgaAe3Mrt6G4tMKZ4YLU9MnsTLZCV_SUQcf-asqgvppo4VJoDVLdj4beuHunu0djNlO_vzYb5c1&t=ffffffffb1d0f179

Payload:
Jw6tUGWnA15YEa3ai3FadGNXHx_DYc5p546xV4lr7BBOr0hJBeoR4VyPxP2lYb82jFgF-SGHgVDsqfQJNr54W8-PvQSburFzEXgaAe3Mrt6G4tMKZ4YLU9MnsTLZCV_SUQcf-asqgvppo4VJoDVLdj4beuHunu0djNlO_vzYb5c1

They seem to be all the same

**Comment by marcolinux46** [comment]
Also from different device i received this page

![image](https://github.com/Tib612/pluxee-api/assets/65719155/7f05d00c-15bd-497a-8f89-247616752504)

**Comment by marcolinux46** [comment]
Hi @Tib612 ,

Everything Is ok?
Do you need help?

**Comment by Tib612** [comment]
Hi,
I have implemented the parsing of the HTML files to extract the balance and transactions.
I'm trying to make to login work now.
Concerning the two factor authentication, I'm leaving it for later.
Also, I found a temporary fix for the SSL certificate error. But it will be useless for non-Belgian user anyway.

**Comment by marcolinux46** [comment]
Very good news.
When you need to do some tests let me know

**Comment by marcolinux46** [comment]
Hi @Tib612 any news?

**Comment by Tib612** [comment]
Hi Marco,
Sorry for the delayed response.
I could't make the login work as the login process is too complex. I tried another approach using selenium and playwright but I was stuck at the captcha.

I don't know how to make it work for non-Belgian users. Feel free to tell me if you find anything.

Thanks for reporting the SSL Error though. This one has been fixed and Belgian users will be able to continue using the api.

Sorry I could't help...

**Comment by marcolinux46** [comment]
Hi @Tib612 ,

i just tried to use selenium to resolve the captcha but unsuccessfully.
I hoped you can do it but probably there is something more complex behind the login mechanism for italian users.

Thank you for your help

If i will find something i will let you know.

Regards
