### ISSUE TITLE
Home Assistant integration?

### ISSUE THREAD

**Issue by bugzke** [Tib612/pluxee-api#2]
Hi @Tib612 

I was using a custom component in Home Assistant for importing my Sodexo data: https://github.com/Fllorent0D/ha-custom-component-sodexo-be

Since they switched their name to Pluxee and changed their website this no longer works. In an attempt to fix it I stumbled upon your project (which works great) but I can't seem to figure out how to get the Home Assistant integration right (Python noob) and the original project seems to be dead.

If by any chance you are a Home Assistant user yourself, or want to try this nonetheless: a feature suggestion for creating a custom component for HA from your pluxee-api :-)

**Comment by Tib612** [comment]
Hi bugzke.

Thanks for your suggestion.
The owner of the repo you mentionned is a friend of mine. I'll see with him to find a solution.

I'll inform you when it is done.

**Comment by Tib612** [comment]
Hi @bugzke,

I made a PR on [https://github.com/Fllorent0D/ha-custom-component-sodexo-be](url) which fixes the data retrieval.
You can find my answer on [https://github.com/Fllorent0D/ha-custom-component-sodexo-be/issues/5#issuecomment-2243684155](url)

**Comment by bugzke** [comment]
Thanks! Tested and working flawlessly!

**Comment by Tib612** [comment]
Nice ! Don't hesitate if you see any bug.
